config/routes.rb
Rails.application.routes.draw do

  root to: 'decisions#new'

  resources :decisions, only: [:index, :new, :create, :update, :destroy, :edit] do
    resources :criteria, only: [:index, :new, :create, :destroy]
      resources :answers, only: [:index, :new, :create, :destroy]
  end

  get 'decisions/home' => 'decisions#home', as: :home

  resource :session, only: [:new, :create, :destroy]

  get 'users' => 'users#index', as: :users
  get 'users/new' => 'users#new', as: :new_user
  post 'users' => 'users#create'
  get 'users/:id' => 'users#show', as: :user
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  put 'users/:id' => 'users#update'
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy'

end

app/models/decision.rb
class Decision
  include Mongoid::Document
  field :text, type: String

  belongs_to :user
  has_many :criteria
  has_many :answers

  accepts_nested_attributes_for :criteria

	def criterion_answers
      CriterionAnswer.find answer_ids
    end
    #accepts_nested_attributes_for :answers

    def criterion_answer_ids
      ret = []
      self.criteria.each do |c|
        c.criterion_answer.each do |ca|
          ret.push ca.id
        end
      end
      ret 
    end
  
end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  def home
     @user = User.new
     @is_login = true
  end

  def current_user
      if User && :user_id && session[:user_id]
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      else
        return false
      end
  end
 
  # def current_user
  #     @current_user ||= User.find(session[:user_id]) if session[:user_id]
  # end

  def index
    if !current_user
      redirect_to home_path
      return
    end
  #	@decisions = Decision.where(user_id: current_user.id)
    @decisions = current_user.decisions
  end

  def new
  	@decision = Decision.new
    @user = User.new
    @is_login = true
    @decision.criteria.build
  end

  def create
    if !current_user
      redirect_to new_session_path
      return
    end
    decision = current_user.decisions.new(
  		decision_params
  		)
    # with this decision object, attach it to the user.
    decision.user = current_user
  	if decision.save
	  	redirect_to decisions_path
  	end
  end

  def update
    Decision.find(params[:id]).update
      (decision_params)
  end

  def destroy
  	Decision.find(params[:id]).destroy
      if Decision.count < 1
      redirect_to new_decision_path
      else
      redirect_to decisions_path
    end
  end

  private
    def decision_params
      params.require(:decision).permit(:text, :criteria_attributes => [:text, :importance])


    end

end

app/helpers/decisions_helper.rb
module DecisionsHelper
end

app/views/decisions/home.html.erb
<div class="container">


	<h1 class="text-center">Welcome to AnswerGuru.</h1>
<!-- 	<h3 class="text-center">Sign up to get help making a decision!</h3> -->

	<div class="signUpForm text-center">

		<%= button_to "Sign up here!", new_user_path, method: :get, :class => "text-center btn btn-default btn-md btn-green" %>
		<%#= form_for @user do |f| %>
			<%#= f.text_field :name, placeholder: "What is your name?" %> 
			<%# f.text_field :email, placeholder: "Email" %>
			<%#= f.password_field :password, placeholder: "password..." %>
			<%#= f.password_field :password_confirmation, placeholder: "re-enter password" %>
			<%#= f.submit "Sign up!", :class => "btn btn-default btn-md btn-blue signBtn" %>
		<%# end  if !current_user %>

	</div>
	
	<br /><br />

	
	<h3 class="text-center">Already have an account? </h3>
	<h4 class="text-center">Sign in below.</h4>

		<div class="logIn text-center ">

			<h1 class="text-center">Log in</h1><br />
			<%= form_for @user, {url: session_path} do |f| %>
				<%= f.text_field :email, placeholder: "Email", :class => "inputEmail" %><br />
				<%= f.password_field :password, placeholder: "password" %><br />
				<%= f.submit "Log in", :class => "btn btn-default btn-md btn-blue" %>
			<% end %>

</div>

app/views/decisions/index.html.erb
<div class="container">

<h1 class="text-center">My Decisions</h1>

<ul class="decisionsList">

<% @decisions.each do |d| %>

	<li>
		<div class="col-md-6 decTxt">
			<%= link_to d.text, decision_criteria_path(d.id) %>
		</div>
		<div class="col-md-2">
		</div>
		<div class="col-md-3">
			<%= link_to "make this decision!", decision_criteria_path(d.id), :class => "btn btn-default btn-md btn-green wider" %>
		</div>
		<div class="col-md-1">
			<%= button_to " X ", decision_path(d.id), :class => "btn btn-default btn-md btn-rederer", method: :delete %>
		</div>
		<br /><br />
	</li>

<% end %>

</ul>

<br />

	<div class="addCrit text-center">
		
		<%= link_to "Add a new decision", new_decision_path if current_user %>
	</div>

</div>

app/views/decisions/new.html.erb
<!-- <div class="topBar">

	<button onclick="window.location.href='/decisions'" class="btn btn-default btn-md btn-bluer prev">See Previous Decisions</button>

</div> -->

<div class="container newD">

	<h1 class="text-center">Let's help you decide.</h1>

	<div class="decisionInput text-center">

	<%= form_for @decision do |f| %>
		<%= f.text_field :text, :class => "decisionInputTxt", placeholder: "What's the decision?" %> <br />
		<%= f.submit "Answer", :class => "btn btn-default btn-md btn-bluer" %>
	<% end %>

	</div>

</div>