config/routes.rb
Rails.application.routes.draw do

  root to: 'decisions#new'

  resources :decisions, only: [:index, :new, :create, :update, :destroy, :edit] do
    resources :criteria, only: [:index, :new, :create, :destroy]
      resources :answers, only: [:index, :new, :create, :destroy]
  end

  get 'decisions/home' => 'decisions#home', as: :home

  resource :session, only: [:new, :create, :destroy]

  get 'users' => 'users#index', as: :users
  get 'users/new' => 'users#new', as: :new_user
  post 'users' => 'users#create'
  get 'users/:id' => 'users#show', as: :user
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  put 'users/:id' => 'users#update'
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy'

end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  field :email, type: String
  field :name, type: String
  field :password_digest, type: String
  field :is_active, type: Mongoid::Boolean, default: true

  has_secure_password

  has_many :decisions
  has_many :answers

  #has_many :answers
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    # @users = User.all
    @users = User.where(is_active: true)
  end

  # Set
  def new
    @user = User.new
  end

  def current_user
    if User && :user_id && session[:user_id]
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    else
      return false
    end
  end
  
  # Spike
  def create
    user = User.new(params.require(:user).permit(:name, :email, :password, :password_confirmation))
    if user.save
      redirect_to users_path
    end
  end

  def show

  end

  def edit

  end

  def update
    @user = User.find(params[:id])
      if current_user != @user
        if 
          current_user 
          redirect_to new_decision_path(current_user)
        else 
          redirect_to new_session_path #send them to login page/ make user login in
      end

      elsif
        @user.update_attributes(params.require(:user).permit(:name, :email, :is_active))
        redirect_to users_path
      else
        render :edit
      end

  end

  def destroy
    @user = User.find(params[:id])
    @user.is_active = false 
    @user.save
    # Exactly the same idea as this little number:
#    User.find_by(id: params[:id])
      redirect_to users_path
  end

  def reactivate

    @user = User.find(params[:id])

  end



end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Welcome to the Decisionator</h1>

<ul>
<% @users.each do |u| %>
	<li>
		<%= link_to u.name, edit_user_path(u.id) %>
	<!-- 	<%= button_to "X", user_path(u.id), method: :delete %> -->
	</li>
<% end %>
</ul>

app/views/users/new.html.erb
<div class="container">

	<h1 class="text-center">Welcome to AnswerGuru.</h1>
	<h3 class="text-center">Sign up to get help making a decision!</h3>

	<div class="signUpForm text-center">

		<%= form_for @user do |f| %>
			<%= f.text_field :name, placeholder: "What is your name?" %> 
			<%= f.text_field :email, placeholder: "Email" %>
			<%= f.password_field :password, placeholder: "password..." %>
			<%= f.password_field :password_confirmation, placeholder: "re-enter password" %>
			<%= f.submit "submit", :class => "btn btn-default btn-md btn-blue sub" %>
		<% end %>

	</div>
	
	<br /><br />
<!-- 	<h3 class="text-center">Already have an account? </h3>
	<h4 class="text-center">Sign in below.</h4>

		<div class="logIn text-center ">

			<h1 class="text-center">Log in</h1><br />

			<%= form_for @user, {url: session_path} do |f| %>
				<%= f.text_field :email, placeholder: "Email", :class => "inputEmail" %><br />
				<%= f.password_field :password, placeholder: "password" %><br />
				<%= f.submit "Log in", :class => "btn btn-default btn-md btn-blue" %>
			<% end %>

		</div> -->



	<!-- <div class="formTwo">
		<form role="form">
		  <div class="form-group">
		    <label for="exampleInputEmail1">Name</label>
		    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Name">
		  </div>
		  <div class="form-group">
		    <label for="exampleInputEmail1">Email address</label>
		    <input type="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email">
		  </div>
		  <div class="form-group">
		    <label for="exampleInputPassword1">Password</label>
		    <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
		  </div>
		  <button type="submit" class="btn btn-default">Submit</button>
		</form>
	</div> -->

</div>

app/views/users/reactivate.html.erb
<%= form_for @user do |f| %>
<!-- 	<%= f.check_box: is_active %> -->
	<%= f.text_field :email, placeholder: "Email" %> <br />
	<%= f.password_field :password, placeholder: "password..." %><br />
	<%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>All Users</h1>