config/routes.rb
Rails.application.routes.draw do

  root to: 'decisions#new'

  resources :decisions, only: [:index, :new, :create, :update, :destroy, :edit] do
    resources :criteria, only: [:index, :new, :create, :destroy]
      resources :answers, only: [:index, :new, :create, :destroy]
  end

  get 'decisions/home' => 'decisions#home', as: :home

  resource :session, only: [:new, :create, :destroy]

  get 'users' => 'users#index', as: :users
  get 'users/new' => 'users#new', as: :new_user
  post 'users' => 'users#create'
  get 'users/:id' => 'users#show', as: :user
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  put 'users/:id' => 'users#update'
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy'

end

app/views/layouts/_nav.html.erb
<nav class="myNavBar navbar navbar-default" role="navigation" style="border-radius:none !important">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>  
      <a class="navbar-brand myTitle" href="/"><strong>Answer<span class="guru">Guru</span></strong></a>
      <ul class="nav navbar-nav navbar-left navLinks">
        <%#= form_for @user, {url: new_user_path} do |f| %>
          <li><%#= button_to "Sign up", new_user_path, :class => "btn btn-default btn-md btn-log", :method :get %></li>
        <%# end %>
      </ul>
    </div>

     <ul class="nav navbar-nav navbar-right navLinks">
        <% if current_user %>  
          <li class="navLinks"><%= button_to "Log out", session_path, method: :delete, :class => "btn btn-default btn-md btn-greene" %></li>
        <% else %>
          <li>
            <%= button_to "Sign up!", new_user_path, method: :get, :class => "btn btn-default btn-md btn-greene" %>
          </li>
          <li>
            <%= button_to "Log in", new_session_path, method: :get, :class => "btn btn-default btn-md btn-greene" %>
          </li>
        <% end %>

        <%# if current_user %>
          <li class="navLinks">
              <%#= button_to "Log out", session_path, method: :delete %>
          </li>
        <%# else %>
          
        <%#= form_for @user, {url: session_path} do |f| %>
            <li class="navLinks">
              <%#= f.text_field :email, placeholder: "Email", :class => "inputEmailer" %> 
              <%#= f.password_field :password, placeholder: "password", :class => "inputEmaile" %> 
              <%#= f.submit "Log in", :class => "btn btn-default btn-md btn-grey" %>
            </li>
          <%# end %>
        <%# end %>
      </ul>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%# if current_user %>  
          <li class="navLinks"><a href="/decisions/new">New Decision</a></li>
        <%# else %>
          <li></li>
        <%# end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <title>AnswerGuru</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>

	<body>

		<header>

			<%= render 'layouts/nav' %>

		</header>

			<%= yield %>

	</body>

</html>
	